const tags = {

  Skills: {
    table: 'skills',
    primary: 'Id',
    name: 'Name',
    source_id: 'SkillId',
    type: 'text',
    source_table: 'interview_skills',
    data: 'Name,Id,Approved',
  },
  Books: {
    table: 'books',
    primary: 'Id',
    name: 'Name',
    source_id: 'BookId',
    type: 'text',
    source_table: 'interview_books',
    data: 'Name,Id,Approved',
  },
  Courses: {
    table: 'courses',
    primary: 'Id',
    name: 'Name',
    source_id: 'CourseId',
    type: 'text',
    source_table: 'interview_courses',
    data: 'Name,Id,Approved',
  },
  Websites: {
    table: 'websites',
    primary: 'Id',
    name: 'Link',
    source_id: 'WebsiteId',
    type: 'url',
    source_table:	'interview_websites',
    data:	'Link AS Name,Id,Approved',
  },
  Videos: {
    table: 'videos',
    primary:	'Id',
    name: 'Link',
    source_id:	'VideoId',
    type:	'url',
    source_table:	'interview_videos',
    data:	'Link AS Name,Id,Approved',
  },
  Coaching: {
    table: 'coaching_classes',
    primary:	'Id',
    name: 'Name',
    source_id:	'CoachingId',
    type:	'text',
    source_table:	'interview_coaching',
    data:	'Name,Id,Approved',
  },
  JobProfile:	{
    table: 'job_profiles',
    primary:	'Id',
    name: 'Name',
    source_id:	'JobProfileId',
    type:	'text',
    source_table:	'interview_reviews',
    data:	'Name,Id,Approved',
  },
  Company:	{
    table: 'companies',
    primary:	'CompanyId',
    name: 'Name',
    type:	'text',
    source_id:	'CompanyId',
    source_table:	'interview_reviews',
    data:	'Name,ShortName,CompanyId AS Id',
  },
  College:	{
    table: 'colleges',
    primary:	'Id',
    name: 'Name',
    type:	'text',
    source_id:	'CollegeId',
    source_table:	'user',
    data:	'Name,Id',
  },
  Industry: {
    table: 'industry',
    primary:	'IndustryId',
    name: 'IndustryName',
    type:	'text',
    source_id:	'IndustryId',
    source_table:	'companies',
    data:	'IndustryName AS Name,IndustryId AS Id',
  },
  Sector: {
    table: 'sectors',
    primary:	'Id',
    name: 'Name',
    type:	'text',
    source_id:	'SectorId',
    source_table:	'companies',
  },
  Location: {
    table: 'city_list',
    primary: 'Id',
    name: 'Name',
    type: 'text',
    source_id: 'JobLocation',
    source_table: 'company_reviews',
  },
};
const locations = ['India', 'Achalpur', 'Achhnera', 'Adalaj', 'Adilabad', 'Adityapur', 'Adoni', 'Adoor',
  'Adra', 'Adyar', 'Afzalpur', 'Agartala', 'Agra', 'Ahmedabad', 'Ahmednagar', 'Aizawl', 'Ajmer', 'Akola',
  'Akot', 'Alappuzha', 'Aligarh', 'AlipurdUrban Agglomerationr', 'Alirajpur', 'Allahabad', 'Alwar',
  'Amalapuram', 'Amalner', 'Ambattur', 'Ambejogai', 'Ambernath', 'Ambikapur', 'Amravati', 'Amreli', 'Amritsar',
  'Amroha', 'Anakapalle', 'Anand', 'Anantapur', 'Anantnag', 'Anjangaon', 'Anjar', 'Ankleshwar', 'Arakkonam',
  'Arambagh', 'Araria', 'Arrah', 'Arsikere', 'Aruppukkottai', 'Arvi', 'Arwal', 'Asansol', 'Asarganj',
  'Ashok Nagar', 'Athni', 'Attingal', 'Aurangabad', 'Avadi', 'Azamgarh', 'Baddi', 'Bagaha', 'Bageshwar',
  'Bahadurgarh', 'Baharampur', 'Bahraich', 'Balaghat', 'Balangir', 'Baleshwar Town', 'Ballari', 'Bally',
  'Balurghat', 'Bangalore', 'Bankura', 'Bapatla', 'Baramula', 'Baranagar', 'Barasat', 'Barbil', 'Bardhaman',
  'Bareilly', 'Bargarh', 'Barh', 'Baripada Town', 'Barmer', 'Barnala', 'Barpeta', 'Batala', 'Bathinda',
  'Begusarai', 'Belagavi', 'Belgaum', 'Bellampalle', 'Bellary', 'Belonia', 'Bengaluru', 'Bettiah',
  'BhabUrban Agglomeration', 'Bhadrachalam', 'Bhadrak', 'Bhagalpur', 'Bhainsa', 'Bharatpur', 'Bharuch',
  'Bhatapara', 'Bhatpara', 'Bhavnagar', 'Bhawanipatna', 'Bheemunipatnam', 'Bhilai', 'Bhilai Nagar', 'Bhilwara', 'Bhimavaram', 'Bhiwandi', 'Bhiwani', 'Bhongir', 'Bhopal', 'Bhubaneswar', 'Bhuj', 'Bihar Sharif', 'Bijapur', 'Bikaner', 'Bilaspur', 'Bobbili', 'Bodhan', 'Bokaro', 'Bokaro Steel City', 'Bongaigaon City', 'Brahmapur', 'Bulandshahr', 'Buxar', 'Byasanagar', 'Chaibasa', 'Chalakudy', 'Chandausi', 'Chandigarh', 'Chandrapur', 'Changanassery', 'Charkhi Dadri', 'Chatra', 'Chennai', 'Cherthala', 'Chhapra', 'Chikkamagaluru', 'Chilakaluripet', 'Chirala', 'Chirkunda', 'Chirmiri', 'Chittoor', 'Chittur-Thathamangalam', 'Coimbatore', 'Cuttack', 'Dalli-Rajhara', 'Darbhanga', 'Darjiling', 'Davanagere', 'Deesa', 'Dehradun', 'Dehri-on-Sone', 'Delhi', 'Delhi NCR', 'Deoghar', 'Dewas', 'Dhamtari', 'Dhanbad', 'Dharmanagar', 'Dharmavaram', 'Dhenkanal', 'Dhoraji', 'Dhubri', 'Dhule', 'Dhuri', 'Dibrugarh', 'Dimapur', 'Diphu', 'Dubai', 'Dumka', 'Dumraon', 'Durg', 'Durgapur', 'Eluru', 'English Bazar', 'Erode', 'Etawah', 'Faridabad', 'Faridkot', 'Farooqnagar', 'Farrukhabad', 'Fatehabad', 'Fatehpur Sikri', 'Fazilka', 'Firozabad', 'Firozpur', 'Firozpur Cantt.', 'Forbesganj', 'Gadwal', 'Gandhidham', 'Gandhinagar', 'Gangarampur', 'Ganjbasoda', 'Gaya', 'Ghaziabad', 'Giridih', 'Goa', 'Goalpara', 'Gobichettipalayam', 'Gobindgarh', 'Godhra', 'Gohana', 'Gokak', 'Gooty', 'Gopalganj', 'Gopalpur', 'Gorakhpur', 'Greater Noida', 'Gudivada', 'Gudur', 'Gulbarga', 'Gumia', 'Guntakal', 'Guntur', 'Gurdaspur', 'Gurgaon', 'Guruvayoor', 'Guwahati', 'Gwalior', 'Habra', 'Hajipur', 'Haldwani-cum-Kathgodam', 'Hansi', 'Hapur', 'Hardoi ', 'Hardwar', 'Haridwar', 'Hazaribag', 'Hindupur', 'Hisar', 'Hoshiarpur', 'Hosur', 'Howrah', 'Hubballi-Dharwad', 'Hubli-Dharwad', 'Hugli-Chinsurah', 'Hyderabad', 'Ichalkaranji', 'Imphal', 'Indore', 'Itarsi', 'Jabalpur', 'Jagdalpur', 'Jaggaiahpet', 'Jagraon', 'Jagtial', 'Jaipur', 'Jalandhar', 'Jalandhar Cantt.', 'Jalgaon', 'Jalna', 'Jalpaiguri', 'Jamalpur', 'Jammalamadugu', 'Jammu', 'Jamnagar', 'Jamshedpur', 'Jamui', 'Jangaon', 'Jatani', 'Jehanabad', 'Jhansi', 'Jhargram', 'Jharsuguda', 'Jhumri Tilaiya', 'Jind', 'Jodhpur', 'Jorhat', 'Junagadh', 'Kadapa', 'Kadi', 'Kadiri', 'Kagaznagar', 'Kailasahar', 'Kaithal', 'Kakinada', 'Kalimpong', 'Kalpi', 'Kalyan-Dombivali', 'Kamareddy', 'Kamarhati', 'Kancheepuram', 'Kandukur', 'Kanhangad', 'Kannur', 'Kanpur', 'Kapadvanj', 'Kapurthala', 'Karaikal', 'Karawal Nagar', 'Karimganj', 'Karimnagar', 'Karjat', 'Karnal', 'Karur', 'Karwar', 'Kasaragod', 'Kashipur', 'KathUrban Agglomeration', 'Katihar', 'Kavali', 'Kayamkulam', 'Kendrapara', 'Kendujhar', 'Keshod', 'Khair', 'Khambhat', 'Khammam', 'Khanna', 'Kharagpur', 'Kharar', 'Khowai', 'Kirari Suleman Nagar', 'Kishanganj', 'Kochi', 'Kodungallur', 'Kohima', 'Kolar', 'Kolhapur', 'Kolkata', 'Kollam', 'Koratla', 'Korba', 'Kot Kapura', 'Kota', 'Kothagudem', 'Kottayam', 'Kovvur', 'Koyilandy', 'Kozhikode', 'Kulti', 'Kunnamkulam', 'Kurnool', 'Kyathampalle', 'Lachhmangarh', 'Ladnu', 'Ladwa', 'Lahar', 'Laharpur', 'Lakheri', 'Lakhimpur', 'Lakhisarai', 'Lakshmeshwar', 'Lal Gopalganj Nindaura', 'Lalganj', 'Lalgudi', 'Lalitpur', 'Lalsot', 'Lanka', 'Lar', 'Lathi', 'Latur', 'Lilong', 'Limbdi', 'Lingsugur', 'Loha', 'Lohardaga', 'Lonar', 'Lonavla', 'Longowal', 'Loni', 'Losal', 'Lucknow', 'Ludhiana', 'Lumding', 'Lunawada', 'Lunglei', 'Macherla', 'Machilipatnam', 'Madanapalle', 'Maddur', 'Madhepura', 'Madhubani', 'Madhugiri', 'Madhupur', 'Madikeri', 'Madurai', 'Magadi', 'Mahad', 'Mahalingapura', 'Maharajganj', 'Maharajpur', 'Mahasamund', 'Mahbubnagar', 'Mahe', 'Mahemdabad', 'Mahendragarh', 'Mahesana', 'Maheshtala', 'Mahidpur', 'Mahnar Bazar', 'Mahuva', 'Maihar', 'Mainaguri', 'Makhdumpur', 'Makrana', 'Malaj Khand', 'Malappuram', 'Malavalli', 'Malda', 'Malegaon', 'Malerkotla', 'Malkangiri', 'Malkapur', 'Malout', 'Malpura', 'Malur', 'Manachanallur', 'Manasa', 'Manavadar', 'Manawar', 'Mancherial', 'Mandalgarh', 'Mandamarri', 'Mandapeta', 'Mandawa', 'Mandi', 'Mandi Dabwali', 'Mandideep', 'Mandla', 'Mandsaur', 'Mandvi', 'Mandya', 'Manendragarh', 'Maner', 'Mangaldoi', 'Mangalore', 'Mangaluru', 'Mangalvedhe', 'Manglaur', 'Mango', 'Mangrol', 'Mangrulpir', 'Manihari', 'Manjlegaon', 'Mankachar', 'Manmad', 'Mansa', 'Manuguru', 'Manvi', 'Manwath', 'Mapusa', 'Margao', 'Margherita', 'Marhaura', 'Mariani', 'Marigaon', 'Markapur', 'Marmagao', 'Masaurhi', 'Mathabhanga', 'Mathura', 'Mattannur', 'Mau', 'Mauganj', 'Mavelikkara', 'Mavoor', 'Mayang Imphal', 'Medak', 'Medininagar (Daltonganj)', 'Medinipur', 'Meerut', 'Mehkar', 'Memari', 'Merta City', 'Mhaswad', 'Mhow Cantonment', 'Mhowgaon', 'Mihijam', 'Mira-Bhayandar', 'Mirganj', 'Miryalaguda', 'Mirzapur', 'Modasa', 'Modinagar', 'Moga', 'Mohali', 'Mokameh', 'Mokokchung', 'Monoharpur', 'Moradabad', 'Morena', 'Morinda, India', 'Morshi', 'Morvi', 'Motihari', 'Motipur', 'Mount Abu', 'Mudabidri', 'Mudalagi', 'Muddebihal', 'Mudhol', 'Mukerian', 'Mukhed', 'Muktsar', 'Mul', 'Mulbagal', 'Multai', 'Mumbai', 'Mundargi', 'Mundi', 'Mungeli', 'Munger', 'Murliganj', 'Murshidabad', 'Murtijapur', 'Murwara (Katni)', 'Musabani', 'Mussoorie', 'Muvattupuzha', 'Muzaffarnagar', 'Muzaffarpur', 'Mysore', 'Nabadwip', 'Nabarangapur', 'Nabha', 'Nadbai', 'Nadiad', 'Nagaon', 'Nagapattinam', 'Nagar', 'Nagari', 'Nagarkurnool', 'Nagaur', 'Nagda', 'Nagercoil', 'Nagina', 'Nagla', 'Nagpur', 'Nahan', 'Naharlagun', 'Naidupet', 'Naihati', 'Naila Janjgir', 'Nainital', 'Nainpur', 'Najibabad', 'Nakodar', 'Nakur', 'Nalbari', 'Namagiripettai', 'Namakkal', 'Nanded', 'Nanded-Waghala', 'Nandgaon', 'Nandivaram-Guduvancheri', 'Nandura', 'Nandurbar', 'Nandyal', 'Nangal', 'Nanjangud', 'Nanjikottai', 'Nanpara', 'Narasapuram', 'Narasaraopet', 'Naraura', 'Narayanpet', 'Nargund', 'Narkatiaganj', 'Narkhed', 'Narnaul', 'Narsinghgarh', 'Narsipatnam', 'Narwana', 'Nashik', 'Nasirabad', 'Natham', 'Nathdwara', 'Naugachhia', 'Naugawan Sadat', 'Nautanwa', 'Navalgund', 'Navi Mumbai', 'Navsari', 'Nawabganj', 'Nawada', 'Nawanshahr', 'Nawapur', 'Nedumangad', 'Neem-Ka-Thana', 'Neemuch', 'Nehtaur', 'Nelamangala', 'Nellikuppam', 'Nellore', 'Nepanagar', 'New Delhi', 'Neyveli (TS)', 'Neyyattinkara', 'Nidadavole', 'Nilambur', 'Nilanga', 'Nimbahera', 'Nirmal', 'Niwai', 'Niwari', 'Nizamabad', 'Nohar', 'Noida', 'Nokha', 'Nongstoin', 'Noorpur', 'North Dumdum', 'North Lakhimpur', 'Nowgong', 'Nowrozabad (Khodargama)', 'Nuzvid', "O' Valley", 'Obra', 'Oddanchatram', 'Ongole', 'Orai', 'Osmanabad', 'Ottappalam', 'Ozar', 'Ozhukarai', 'P.N.Patti', 'Pachora', 'Pachore', 'Pacode', 'Padmanabhapuram', 'Padra', 'Padrauna', 'Paithan', 'Pakaur', 'Palacole', 'Palai', 'Palakkad', 'Palampur', 'Palani', 'Palanpur', 'Palasa Kasibugga', 'Palghar', 'Pali', 'Palia Kalan', 'Palitana', 'Palladam', 'Pallapatti', 'Pallikonda', 'Palwal', 'Palwancha', 'Panagar', 'Panagudi', 'Panaji', 'Panamattom', 'Panchkula', 'Panchla', 'Pandharkaoda', 'Pandharpur', 'Pandhurna', 'PandUrban Agglomeration', 'Panihati', 'Panipat', 'Panna', 'Panniyannur', 'Panruti', 'Panvel', 'Pappinisseri', 'Paradip', 'Paramakudi', 'Parangipettai', 'Parasi', 'Paravoor', 'Parbhani', 'Pardi', 'Parlakhemundi', 'Parli', 'Partur', 'Parvathipuram', 'Pasan', 'Paschim Punropara', 'Pasighat', 'Patan', 'Pathanamthitta', 'Pathankot', 'Pathardi', 'Pathri', 'Patiala', 'Patna', 'Patratu', 'Pattamundai', 'Patti', 'Pattran', 'Pattukkottai', 'Patur', 'Pauni', 'Pauri', 'Pavagada', 'Pedana', 'Peddapuram', 'Pehowa', 'Pen', 'Perambalur', 'Peravurani', 'Peringathur', 'Perinthalmanna', 'Periyakulam', 'Periyasemur', 'Pernampattu', 'Perumbavoor', 'Petlad', 'Phagwara', 'Phalodi', 'Phaltan', 'Phillaur', 'Phulabani', 'Phulera', 'Phulpur', 'Phusro', 'Pihani', 'Pilani', 'Pilibanga', 'Pilibhit', 'Pilkhuwa', 'Pimpri-Chinchwad', 'Pindwara', 'Pinjore', 'Pipar City', 'Pipariya', 'Piriyapatna', 'Piro', 'Pithampur', 'Pithapuram', 'Pithoragarh', 'Pollachi', 'Polur', 'Pondicherry', 'Ponnani', 'Ponneri', 'Ponnur', 'Porbandar', 'Porsa', 'Port Blair', 'Powayan', 'Prantij', 'Pratapgarh', 'Prithvipur', 'Proddatur', 'Puducherry', 'Pudukkottai', 'Pudupattinam', 'Pukhrayan', 'Pulgaon', 'Puliyankudi', 'Punalur', 'Punch', 'Pune', 'Punganur', 'Punjaipugalur', 'Puranpur', 'Puri', 'Purna', 'Purnia', 'PurqUrban Agglomerationzi', 'Purulia', 'Purwa', 'Pusad', 'Puthuppally', 'Puttur', 'Qadian', 'Raayachuru', 'Rabkavi Banhatti', 'Radhanpur', 'Rae Bareli', 'Rafiganj', 'Raghogarh-Vijaypur', 'Raghunathganj', 'Raghunathpur', 'Rahatgarh', 'Rahuri', 'Raichur', 'Raiganj', 'Raigarh', 'Raikot', 'Raipur', 'Rairangpur', 'Raisen', 'Raisinghnagar', 'Rajagangapur', 'Rajahmundry', 'Rajakhera', 'Rajaldesar', 'Rajam', 'Rajampet', 'Rajapalayam', 'Rajauri', 'Rajgarh', 'Rajgarh (Alwar)', 'Rajgarh (Churu)', 'Rajgir', 'Rajkot', 'Rajnandgaon', 'Rajpipla', 'Rajpur Sonarpur', 'Rajpura', 'Rajsamand', 'Rajula', 'Rajura', 'Ramachandrapuram', 'Ramagundam', 'Ramanagaram', 'Ramanathapuram', 'Ramdurg', 'Rameshwaram', 'Ramganj Mandi', 'Ramgarh', 'Ramnagar', 'Ramngarh', 'Rampur', 'Rampur Maniharan', 'Rampura Phul', 'Rampurhat', 'Ramtek', 'Ranaghat', 'Ranavav', 'Ranchi', 'Ranebennuru', 'Rangia', 'Rania', 'Ranibennur', 'Ranipet', 'Rapar', 'Rasipuram', 'Rasra', 'Ratangarh', 'Rath', 'Ratia', 'Ratlam', 'Ratnagiri', 'Rau', 'Raurkela', 'Raver', 'Rawatbhata', 'Rawatsar', 'Raxaul Bazar', 'Rayachoti', 'Rayadurg', 'Rayagada', 'Reengus', 'Rehli', 'Renigunta', 'Renukoot', 'Reoti', 'Repalle', 'Revelganj', 'Rewa', 'Rewari', 'Rishikesh', 'Risod', 'Robertsganj', 'Robertson Pet', 'Rohtak', 'Ron', 'Roorkee', 'Rosera', 'Rourkela', 'Rudauli', 'Rudrapur', 'Rupnagar', 'Sabalgarh', 'Sadabad', 'Sadalagi', 'Sadasivpet', 'Sadri', 'Sadulpur', 'Sadulshahar', 'Safidon', 'Safipur', 'Sagar', 'Sagara', 'Sagwara', 'Saharanpur', 'Saharsa', 'Sahaspur', 'Sahaswan', 'Sahawar', 'Sahibganj', 'Sahjanwa', 'Saidpur', 'Saiha', 'Sailu', 'Sainthia', 'Sakaleshapura', 'Sakti', 'Salaya', 'Salem', 'Salur', 'Samalkha', 'Samalkot', 'Samana', 'Samastipur', 'Sambalpur', 'Sambhal', 'Sambhar', 'Samdhan', 'Samthar', 'Sanand', 'Sanawad', 'Sanchore', 'Sandi', 'Sandila', 'Sanduru', 'Sangamner', 'Sangareddy', 'Sangaria', 'Sangli', 'Sangli-Miraj & Kupwad', 'Sangole', 'Sangrur', 'Sankarankovil', 'Sankari', 'Sankeshwara', 'Santipur', 'Sarangpur', 'Sardarshahar', 'Sardhana', 'Sarni', 'Sarsod', 'Sasaram', 'Sasvad', 'Satana', 'Satara', 'Sathyamangalam', 'Satna', 'Sattenapalle', 'Sattur', 'Saunda', 'Saundatti-Yellamma', 'Sausar', 'Savanur', 'Savarkundla', 'Savner', 'Sawai Madhopur', 'Sawantwadi', 'Sedam', 'Sehore', 'Sendhwa', 'Seohara', 'Seoni', 'Seoni-Malwa', 'Shahabad', 'Shahabad, Hardoi', 'Shahabad, Rampur', 'Shahade', 'Shahbad', 'Shahdol', 'Shahganj', 'Shahjahanpur', 'Shahpur', 'Shahpura', 'Shajapur', 'Shamgarh', 'Shamli', 'Shamsabad, Agra', 'Shamsabad, Farrukhabad', 'Shegaon', 'Sheikhpura', 'Shendurjana', 'Shenkottai', 'Sheoganj', 'Sheohar', 'Sheopur', 'Sherghati', 'Sherkot', 'Shiggaon', 'Shikaripur', 'Shikarpur, Bulandshahr', 'Shikohabad', 'Shillong', 'Shimla', 'Shirdi',
  'Shirpur-Warwade', 'Shirur', 'Shishgarh', 'Shivamogga', 'Shivamogga (Shimoga)', 'Shivpuri', 'Sholavandan', 'Sholingur', 'Shoranur', 'Shrigonda', 'Shrirampur', 'Shrirangapattana', 'Shujalpur', 'Siana', 'Sibsagar', 'Siddipet', 'Sidhi', 'Sidhpur', 'Sidlaghatta', 'Sihor', 'Sihora', 'Sikanderpur', 'Sikandra Rao', 'Sikandrabad', 'Sikar', 'Silao', 'Silapathar', 'Silchar', 'Siliguri', 'Sillod', 'Silvassa', 'Simdega', 'Sindagi', 'Sindhagi', 'Sindhnur', 'Singrauli', 'Sinnar', 'Sira', 'Sircilla', 'Sirhind Fatehgarh Sahib', 'Sirkali', 'Sirohi', 'Sironj', 'Sirsa', 'Sirsaganj', 'Sirsi', 'Siruguppa', 'Sitamarhi', 'Sitapur', 'Sitarganj', 'Sivaganga', 'Sivagiri', 'Sivakasi', 'Siwan', 'Sohagpur', 'Sohna', 'Sojat', 'Solan', 'Solapur', 'Sonamukhi', 'Sonepur', 'Songadh', 'Sonipat', 'Sopore', 'Soro', 'Soron', 'South Dumdum', 'Soyagaon', 'Sri Ganganagar', 'Sri Madhopur', 'Srikakulam', 'Srikalahasti', 'Srinagar', 'Srinivaspur', 'Srirampore', 'Srisailam Project (Right Flank Colony) Township', 'Srivilliputhur', 'Sugauli', 'Sujangarh', 'Sujanpur', 'Sullurpeta', 'Sultanganj', 'Sultanpur', 'Sumerpur', 'Sunabeda', 'Sunam', 'Sundargarh', 'Sundarnagar', 'Supaul', 'Surandai', 'Surapura', 'Surat', 'Suratgarh', 'SUrban Agglomerationr', 'Suri', 'Suriyampalayam', 'Suryapet', 'Tadepalligudem', 'Tadpatri', 'Takhatgarh', 'Taki', 'Talaja', 'Talcher', 'Talegaon Dabhade', 'Talikota', 'Taliparamba', 'Talode', 'Talwara', 'Tamluk', 'Tanda', 'Tandur', 'Tanuku', 'Tarakeswar', 'Tarana', 'Taranagar', 'Taraori', 'Tarbha', 'Tarikere', 'Tarn Taran', 'Tasgaon', 'Tehri', 'Tekkalakote', 'Tenali', 'Tenkasi', 'Tenu dam-cum-Kathhara', 'Terdal', 'Tezpur', 'Thakurdwara', 'Thammampatti', 'Thana Bhawan', 'Thane', 'Thanesar', 'Thangadh', 'Thanjavur', 'Tharad', 'Tharamangalam', 'Tharangambadi', 'Theni Allinagaram', 'Thirumangalam', 'Thirupuvanam', 'Thiruthuraipoondi', 'Thiruvalla', 'Thiruvallur', 'Thiruvananthapuram', 'Thiruvarur', 'Thodupuzha', 'Thoothukudi', 'Thoubal', 'Thrissur', 'Thuraiyur', 'Tikamgarh', 'Tilda Newra', 'Tilhar', 'Tindivanam', 'Tinsukia', 'Tiptur', 'Tirora', 'Tiruchendur', 'Tiruchengode', 'Tiruchirappalli', 'Tirukalukundram', 'Tirukkoyilur', 'Tirunelveli', 'Tirupathur', 'Tirupati', 'Tiruppur', 'Tirupur', 'Tirur', 'Tiruttani', 'Tiruvannamalai', 'Tiruvethipuram', 'Tiruvottiyur', 'Tiruvuru', 'Tirwaganj', 'Titlagarh', 'Tittakudi', 'Todabhim', 'Todaraisingh', 'Tohana', 'Tonk', 'Tuensang', 'Tuljapur', 'Tulsipur', 'Tumkur', 'Tumsar', 'Tundla', 'Tuni', 'Tura', 'Uchgaon', 'Udaipur', 'Udaipurwati', 'Udgir', 'Udhagamandalam', 'Udhampur', 'Udumalaipettai', 'Udupi', 'Ujhani', 'Ujjain', 'Ulhasnagar', 'Umarga', 'Umaria', 'Umarkhed', 'Umbergaon', 'Umred', 'Umreth', 'Una', 'Unjha', 'Unnamalaikadai', 'Unnao', 'Upleta', 'Uran', 'Uran Islampur', 'Uravakonda', 'Urmar Tanda', 'Usilampatti', 'Uthamapalayam', 'Uthiramerur', 'Utraula', 'Vadakkuvalliyur', 'Vadalur', 'Vadgaon Kasba', 'Vadipatti', 'Vadnagar', 'Vadodara', 'Vaijapur', 'Vaikom', 'Valparai', 'Valsad', 'Vandavasi', 'Vaniyambadi', 'Vapi', 'Varanasi', 'Varkala', 'Vasai-Virar', 'Vatakara', 'Vedaranyam', 'Vellakoil', 'Vellore', 'Venkatagiri', 'Veraval', 'Vidisha', 'Vijainagar, Ajmer', 'Vijapur', 'Vijayapura', 'Vijayawada', 'Vijaypur', 'Vikarabad', 'Vikramasingapuram', 'Viluppuram', 'Vinukonda', 'Viramgam', 'Virudhachalam', 'Virudhunagar', 'Visakhapatnam', 'Visnagar', 'Viswanatham', 'Vita', 'Vizianagaram', 'Vrindavan', 'Vyara', 'Wadgaon Road', 'Wadhwan', 'Wadi', 'Wai', 'Wanaparthy', 'Wani', 'Wankaner', 'Wara Seoni', 'Warangal', 'Wardha', 'Warhapur', 'Warisaliganj', 'Warora', 'Warud', 'Washim', 'Wokha', 'Yadgir', 'Yamunanagar', 'Yanam', 'Yavatmal', 'Yawal', 'Yellandu', 'Yemmiganur', 'Yerraguntla', 'Yevla', 'Zaidpur', 'Zamania', 'Zira', 'Zirakpur', 'Zunheboto', 'Chakan', 'trivandrum', 'MANESAR', 'Bhiwadi', 'bawal', 'Gurgoan', 'daman', 'Khopoli', 'Balasore', 'Banglore', 'Nasik', 'vizag', 'TRIVANDRUM', 'Cochin', 'Gurugram', 'baroda', 'Dehli', 'Andheri', 'Airoli', 'Lower parel', 'Vashi', 'Powai', 'Vikhroli', 'Bandra', 'ghansoli', 'borivali', 'Chembur', 'Kandivali', 'ghatkopar', 'worli', 'Kalyan', 'Santacruz', 'Bhandup', 'Sakinaka ', 'Kurla', 'Andheri west', 'rabale ', 'Turbhe', 'Vikroli', 'trichy', 'ahemdabad', 'calicut', 'Tuticorin', 'orissa', 'Hospet', 'Tirupathi', 'Vishakapatnam', 'Doha', 'Qatar', 'Tanzania', 'Saudi arabia', 'Muscat', 'Abu Dhabi', 'Dubai', 'Sharjah', 'Ajman', 'Al Ain', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm al-Quwain', 'UAE', 'United Arab Emirates'];

module.exports = {
  tags,
  locations,
};
